import { Inter } from "next/font/google";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;
import Sidebar from "@/components/sidebar";

import Chat from "./chat";

import "../globals.css";
import getCookie from "@/components/getCoockie";

import { AppProvider } from "@/context/context";
import { ResponseProvider } from "@/context/responsecontext";






const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "messages",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className="flex bg-deepdark w-[100%] relative">
        <AppProvider>
          <ResponseProvider>

          
          <Sidebar  />

          <Chat />

          {children}
          </ResponseProvider>
        </AppProvider>
      </body>
    </html>
  );
}
